name: "ZAP API Scan CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 


jobs:

# https://github.com/marketplace/actions/owasp-zap-full-scan
 ubuntu-latest-zap-full-basic-job:
    name: "basic -The OWASP ZAP API Scan to perform Dynamic Application Security Testing (DAST) ubuntu latest"
    runs-on: ubuntu-latest
    steps:
      - name: "ZAP API Scan"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
        # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://testphp.vulnweb.com'    

# https://github.com/marketplace/actions/owasp-zap-full-scan
 ubuntu-latest-zap-full-advanced-job:
    name: "advanced - The OWASP ZAP API Scan to perform Dynamic Application Security Testing (DAST) ubuntu latest"
    runs-on: ubuntu-latest
    steps:
      - name: "ZAP API Scan http://testphp.vulnweb.com"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://testphp.vulnweb.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: "ZAP API Scan http://demo.testfire.net/"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://demo.testfire.net/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'          
      - name: "ZAP API Scan https://dvwa.co.uk/"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://dvwa.co.uk/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: "ZAP API Scan https://ctflearn.com/"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://ctflearn.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'          
      - name: "ZAP API Scan https://ctflearn.com/"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://ctflearn.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a' 
      - name: "ZAP API Scan https://www.gameofhacks.com/"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://www.gameofhacks.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'           
      - name: "ZAP API Scan https://public-firing-range.appspot.com/"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://public-firing-range.appspot.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: "ZAP API Scan http://google-gruyere.appspot.com/"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://google-gruyere.appspot.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'          




